#############################################################################
# Motion counter voordeur buiten
- alias: Count motion voordeur buiten
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002e8d2f1
    from: 'off'
    to: 'on'
  action:
    - service: counter.increment
      entity_id: counter.motion_counteri_voordeur_buiten

#############################################################################
# Motion counter studeerkamer
- alias: Count motion studeerkamer
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002584585
    from: 'off'
    to: 'on'
  action:
    - service: counter.increment
      entity_id: counter.motion_counter_studeerkamer

#############################################################################
# Motion counter overloop
- alias: Count motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00029a5cd2
    from: 'off'
    to: 'on'
  action:
    - service: counter.increment
      entity_id: counter.motion_counter

#############################################################################
# Set brightness to 30% after 22:00 overloop
- alias: overloop licht in de avond
  trigger:
    platform: time
    at: '22:00:00'
  action:
    - service: light.turn_on
      entity_id: light.overloop
      data:
        transition: 300
        brightness_pct: 30

# Set lights to 0% after 00:00 overloop
- alias: overloop licht na 00:00
  trigger:
    platform: time
    at: '23:55:00'
  action:
    - service: light.turn_off
      entity_id: light.overloop
      data:
        transition: 300
        brightness_pct: 0

# Set brightness to 10% when there is motion after 00:00 overloop
- alias: overloop licht in de nacht
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00029a5cd2
    from: 'off'
    to: 'on'
  condition:
    - condition: time
      after: '00:00:00'
    - condition: time
      before: '07:30:00'
  action:
    - service: light.turn_on
      entity_id: light.overloop
      data:
        transition: 5
        brightness_pct: 10
    - delay: 
        seconds: 300
    - service: light.turn_on
      entity_id: light.overloop
      data:
        transition: 300
        brightness_pct: 0
    - delay: 
        seconds: 300
    - service: light.turn_off
      entity_id: light.overloop

# Restore light brightness in the morning overloop
- alias: overloop licht in de ochtend
  trigger:
    platform: time
    at: '07:30:00'
  action:
    - service: light.turn_on
      entity_id: light.overloop
      data:
        transition: 300
        brightness_pct: 100

#############################################################################
# Reset Hue, when it becomes unavailable
- alias: power-off and power-on hue bridge
  trigger:
    platform: state
    entity_id: binary_sensor.check_hue_bridge
    from: 'on'
    to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.plug_158d00024ae109
    - delay: 0:03
    - service: switch.turn_on
      entity_id: switch.plug_158d00024ae109

#############################################################################
# Dimm hue light with xiaomi switch (single click)
- alias: Dimm slaapkamer licht
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d00027c19e9
      click_type: single
  action:
    service: light.turn_on
    entity_id: light.hue_ambiance_slaapkamer
    data_template:
      brightness: >-
        {% if states.light.hue_ambiance_slaapkamer.attributes.brightness %}
          {% if states.light.hue_ambiance_slaapkamer.attributes.brightness - 60 >= 10 %}
            {{states.light.hue_ambiance_slaapkamer.attributes.brightness - 60}}
          {% else %}
            {{states.light.hue_ambiance_slaapkamer.attributes.brightness}}
          {% endif %}
        {% else %}
          10
        {% endif %}

# Turn off hue light with xiaomi switch (long press)
- alias: Uitzetten slaapkamer licht
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d00027c19e9
      click_type: long
  action:
    service: light.turn_off
    entity_id: light.hue_ambiance_slaapkamer

# Increase hue light with xiaomi switch (single click)
- alias: Verlicht slaapkamer licht
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d00027c19e9
      click_type: single
  action:
    service: light.turn_on
    entity_id: light.hue_ambiance_slaapkamer
    data_template:
      brightness: >-
        {% if states.light.hue_ambiance_slaapkamer.attributes.brightness %}
          {% if states.light.hue_ambiance_slaapkamer.attributes.brightness + 60 <= 255 %}
            {{states.light.hue_ambiance_slaapkamer.attributes.brightness + 60}}
          {% else %}
            {{states.light.hue_ambiance_slaapkamer.attributes.brightness}}
          {% endif %}
        {% else %}
          10
        {% endif %}

# Turn on hue light with xiaomi switch (long press)
- alias: Aanzetten slaapkamer licht
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d00027c19e9
      click_type: long
  action:
    service: light.turn_on
    entity_id: light.hue_ambiance_slaapkamer
    data:
      brightness_pct: 100

#############################################################################
# Turn off xiaomi gateway light with xiaomi switch (both press)
- alias: Uitzetten gateway licht
  trigger: 
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_both_158d00027c19e9
      click_type: both
  condition:
    - condition: state
      entity_id: light.gateway_light_7c49ebb18b86
      state: 'on'
  action:
    service: light.turn_off
    entity_id: light.gateway_light_7c49ebb18b86
 
 # Turn on xiaomi gatway light with xiaomi switch (both press)
- alias: Aanzetten gateway licht
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_both_158d00027c19e9
      click_type: both
  condition:
    - condition: state
      entity_id: light.gateway_light_7c49ebb18b86
      state: 'off'
  action:
    service: light.turn_on
    entity_id: light.gateway_light_7c49ebb18b86

#############################################################################
# tracking notifications
- alias: name entered zone
  trigger:
    platform: state
    entity_id: device_tracker.94652dc2aa01, device_tracker.c0eefbe296aa, device_tracker.44c3462e5fdd, device_tracker.8058f897ad84, device_tracker.google_maps_103666873320035558501
  action:     
    service: persistent_notification.create
    data_template:
            message: '{{now().strftime("%Y-%m-%d %H:%M:%S")}}: {{ trigger.to_state.name }} is in {{ trigger.to_state.state }}'

#############################################################################
- alias: Turn on studyroom light when there is movement 
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002584585
    from: 'off'
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-01:00:00'         
      - condition: sun
        before: sunrise 
        before_offset: '01:00:00'
      - condition: numeric_state
        entity_id: sensor.illumination_158d0002584585
        below: 300
  action:
    service: light.turn_on
    entity_id: light.studeerkamer
    data:
      transition: 0
      brightness_pct: 100

- alias: Turn off studyroom light 30 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002584585
    to: 'off'
    for:
      minutes: 30
  action:
    service: light.turn_off
    entity_id: light.studeerkamer

- alias: Turn off studyroom light 1 hour after sunrise
  trigger:
    - platform: sun
      event: sunrise
      offset: "01:00:00"
  action: 
    service: light.turn_off
    entity_id: light.studeerkamer

#############################################################################
- alias: Turn on voordeur buiten light when there is movement 
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002e8d2f1
    from: 'off'
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-00:30:00'         
      - condition: sun
        before: sunrise 
        before_offset: '00:30:00'
  action:
    service: light.turn_on
    entity_id: light.hue_white_light_1_3
    data:
      transition: 5
      brightness_pct: 60

- alias: Turn off voordeur buiten light 5 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002e8d2f1
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    entity_id: light.hue_white_light_1_3
    
- alias: Turn off voordeur buiten light 30 minutes after sunrise
  trigger:
    - platform: sun
      event: sunrise
      offset: "00:30:00"
  action: 
    service: light.turn_off
    entity_id: light.hue_white_light_1_3
###############################################################################
- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "homeassistant/cmnd/+/state"
        payload: "" 
###############################################################################
- alias: "Enable MQTT discovery for all devices"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "homeassistant/cmnd/+/SetOption19"
        payload: "1"
###############################################################################
- alias: "Sonoff state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "homeassistant/cmnd/+/STATUS"
        payload: "2"
############################################################################
- alias: notification after vibrate
  trigger:
    platform: event
    event_type: xiaomi_aqara.movement
    event_data:
      entity_id: binary_sensor.vibration_158d0002b83c5b
      movement_type: vibrate 
  action:
    service: persistent_notification.create
    data_template:
            message: '{{now().strftime("%Y-%m-%d %H:%M:%S")}}: {{ states.binary_sensor.vibration_158d0002b83c5b.attributes["last_action"] }}'

- alias: notification after tilt
  trigger:
    platform: event
    event_type: xiaomi_aqara.movement
    event_data:
      entity_id: binary_sensor.vibration_158d0002b83c5b
      movement_type: tilt
  action:
    service: persistent_notification.create
    data_template:
            message: '{{now().strftime("%Y-%m-%d %H:%M:%S")}}: {{ states.binary_sensor.vibration_158d0002b83c5b.attributes["last_action"] }}'

- alias: notification after free_fall
  trigger:
    platform: event
    event_type: xiaomi_aqara.movement
    event_data:
      entity_id: binary_sensor.vibration_158d0002b83c5b
      movement_type: free_fall
  action:
    service: persistent_notification.create
    data_template:
            message: '{{now().strftime("%Y-%m-%d %H:%M:%S")}}: {{ states.binary_sensor.vibration_158d0002b83c5b.attributes["last_action"] }}'

#############################################################################
- alias: switch Sonoff1 on
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d00025427e0
      click_type: single
  action:
    service: persistent_notification.create
    data_template:
            message: '{{now().strftime("%Y-%m-%d %H:%M:%S")}}: {{ states.binary_sensor.wall_switch_left_158d00025427e0.attributes["last_action"] }}'

- alias: switch Sonoff1 off
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d00025427e0
      click_type: single
  action:
    service: persistent_notification.create
    data_template:
            message: '{{now().strftime("%Y-%m-%d %H:%M:%S")}}: {{ states.binary_sensor.wall_switch_left_158d00025427e0.attributes["last_action"] }}' 