homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  
  # Location required to calculate the time the sun rises and sets
  # Impacts weather/sunrise data (altitude above sea level in meters)
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  
  # metric for Metric, imperial for Imperial
  unit_system: metric
  
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  
  # Customization file
  customize: !include customize.yaml
  
  # C for Celcius, F for Fahrenheit
  temperature_unit: C

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  api_password: !secret api_password
  base_url: !secret my_base_url
  # Letsencrypt duckdns for home-assistant: https://www.splitbrain.org/blog/2017-08/10-homeassistant_duckdns_letsencrypt
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  trusted_networks: 
    - !secret trusted_networks
  ip_ban_enabled: True
  login_attempts_threshold: 25

# to update duckdns dns record dynamicly
duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_access_token

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true
  
# Discover some devices automatically
discovery:

# Media players
media_player:
  - platform: samsungtv
    host: !secret ip_address_samsung_tv_ue32k5600
    port: 8001
    name: Samsung TV UE32K5600

# Xiaomi zigbee gateway
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: !secret xiaomi_mac
      key: !secret xiaomi_key

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

recorder:
  #db_url: !secret ha_db_url
  purge_interval: 1
  purge_keep_days: 14

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor yr:
  - platform: yr
    name: yr
    monitored_conditions:
        - temperature
        - symbol
        - precipitation
        - windSpeed
        - pressure
        - windDirection
        - humidity
        - fog
        - cloudiness
        - lowClouds
        - mediumClouds
        - highClouds
        - dewpointTemperature

sensor:
  - platform: nederlandse_spoorwegen
    email: !secret ns_loginname
    password: !secret ns_password
    routes:
      - name: Utrecht - Amsterdam Zuid
        from: ut
        to: asdz
      - name: Amsterdam Zuid - Utrecht CS
        from: asdz
        to: ut
  - platform: speedtest
    minute:
      - 0
      - 15
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: postnl
    username: !secret post_nl_loginname
    password: !secret post_nl_password
  - platform: systemmonitor
    resources:
      - type: disk_use
        arg: /
      - type: disk_free
        arg: /
      - type: disk_use_percent
        arg: /
      - type: memory_use
      - type: memory_free
      - type: memory_use_percent
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: network_in
        arg: eno1
      - type: network_out
        arg: eno1
      - type: packets_in
        arg: eno1
      - type: packets_out
        arg: eno1
  - platform: dsmr
    host: !secret dsmr_ip_address
    port: 2001
    dsmr_version: 5
  - platform: command_line
    name: SSL cert expiry
    unit_of_measurement: days
    scan_interval: 10800
    # certificate expiry check: https://github.com/Matty9191/ssl-cert-check
    command: "/ssl/ssl-cert-check -b -c /ssl/fullchain.pem | awk '{ print $NF }'"
  - platform: command_line
    name: Host uptime
    unit_of_measurement: days
    scan_interval: 3600
    command: echo $(($(cat /proc/uptime | sed 's/^\([0-9]*\)[ \.].*$/\1/g') / 86400))
  - platform: command_line
    name: Home Assistant uptime
    unit_of_measurement: days
    scan_interval: 3600
    command: echo $(( $(( $(date +%s) - $(ps -e -o etime= -o cmd= -o comm=  | grep home | grep python | awk '{print $1}' |  xargs date +%s -d) )) / 86400 )) 
 
binary_sensor: 
  - platform: command_line
    name: check Hue bridge
    scan_interval: 120
    command: echo $(curl -o /dev/null --silent --head --write-out '%{http_code}' "http://192.168.1.21/debug/clip.html") | sed 's/^.*200.*$/1/g' | sed 's/^.*000.*$/0/g'
    device_class: connectivity
    payload_on: 1
    payload_off: 0

device_tracker:
  - platform: mikrotik
    host: !secret mikrotik_hostname
    port: !secret mikrotik_port
    username: !secret mikrotik_username
    password: !secret mikrotik_password
  - platform: snmp
    host: !secret mikrotik_hostname
    community: !secret mikrotik_snmp_community
    #baseoid: 1.3.6.1.2.1.4.22.1.2.9
    #baseoid: 1.3.6.1.4.1.14988.1.1.1.5
    baseoid: 1.3.6.1.4.1.14988.1.1.1.2.1.1
    track_new_devices: true
    interval_seconds: 3
    home_interval: 5
    consider_home: 180

android_ip_webcam:
  - host: !secret android_ip_webcam_host
    name: webcam
    username: !secret android_ip_webcam_username
    password: !secret android_ip_webcam_password
    scan_interval: 10
    sensors:
      - audio_connections
      - battery_level
      - battery_temp
      - battery_voltage
      - light
      - motion
      - pressure
      - proximity
      - sound
      - video_connections

# Text to speech                      
tts:                                                   
  - platform: google  

# Cloud
cloud:

# Counters
counter:
  motion_counter:
    name: bewegingsteller
    icon: mdi:account

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218
