homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  #latitude: 0
  #longitude: 0
  # Impacts weather/sunrise data (altitude above sea level in meters)
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  # elevation: 0
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  # C for Celcius, F for Fahrenheit
  temperature_unit: C

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
http:
  base_url: !secret my_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  trusted_networks: 
    - !secret trusted_networks
  ip_ban_enabled: True
  login_attempts_threshold: 25

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true
  
# Discover some devices automatically
discovery:

# Media players
media_player:
  - platform: samsungtv
    host: 192.168.1.22
    port: 8001
    name: Samsung TV UE32K5600

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

recorder:
  db_url: !secret ha_db_url
  purge_interval: 1
  purge_keep_days: 2

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor yr:
  - platform: yr
    name: yr
    monitored_conditions:
        - temperature
        - symbol
        - precipitation
        - windSpeed
        - pressure
        - windDirection
        - humidity
        - fog
        - cloudiness
        - lowClouds
        - mediumClouds
        - highClouds
        - dewpointTemperature

sensor:
  - platform: nederlandse_spoorwegen
    email: !secret ns_loginname
    password: !secret ns_password
    routes:
      - name: Utrecht - Amsterdam Zuid
        from: ut
        to: asdz
      - name: Amsterdam Zuid - Utrecht CS
        from: asdz
        to: ut
  - platform: speedtest
    minute:
      - 0
      - 15
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: postnl
    username: !secret post_nl_loginname
    password: !secret post_nl_password
  - platform: systemmonitor
    resources:
      - type: disk_use
        arg: /
      - type: disk_free
        arg: /
      - type: disk_use_percent
        arg: /
      - type: memory_use
      - type: memory_free
      - type: memory_use_percent
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: network_in
        arg: wlan0
      - type: network_out
        arg: wlan0
      - type: packets_in
        arg: wlan0
      - type: packets_out
        arg: wlan0
  - platform: dsmr
    host: 192.168.11.129
    port: 2001
    dsmr_version: 5

# Text to speech                      
tts:                                                   
  - platform: google  

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218