#android_ip_webcam: !include android_ip_webcam.yaml

automation: !include automations.yaml

binary_sensor: !include binary_sensor.yaml

# Enables configuration UI
config:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Counters
counter: !include counters.yaml

# Cloud
cloud:

device_tracker: !include device_tracker.yaml

# Discover some devices automatically
discovery:

# to update duckdns dns record dynamicly
duckdns: !include duckdns.yaml

# Enables the frontend
frontend:

group: !include groups.yaml

homeassistant: !include homeassistant.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http: !include http.yaml

# Show links to resources in log and frontend
#introduction:

logger: !include logger.yaml

# Edit lovelace interface in yaml   
lovelace: !include lovelace.yaml

# Media players
media_player: !include media_player.yaml

# mqtt mosquitto broker
mqtt: !include mqtt.yaml

# Enables support for tracking state changes over time
history:

influxdb: !include influxdb.yaml

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

history_graph: !include history_graph.yaml

luftdaten: !include luftdaten.yaml

notify: !include notify.yaml

person: !include person.yaml

recorder:
  #db_url: !secret ha_db_url
  purge_interval: 1
  purge_keep_days: 3

sensor: !include sensor.yaml

# Weather prediction
sensor yr: !include sensor_yr.yaml

script: !include scripts.yaml

speedtestdotnet: !include speedtest.yaml

# Track the sun
sun:

system_health:

switch: !include switch.yaml

# Text to speech                      
tts:                                                   
  - platform: google  

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true
 
weather:
  - platform: darksky
    api_key: !secret darksky_api_key

# Xiaomi zigbee gateway
xiaomi_aqara: !include xiaomi_aqara.yaml

zone: !include zone.yaml