homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  
  # Location required to calculate the time the sun rises and sets
  # Impacts weather/sunrise data (altitude above sea level in meters)
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  
  # metric for Metric, imperial for Imperial
  unit_system: metric
  
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  
  # Customization file
  customize: !include customize.yaml

  # customize glob file
  customize_glob: !include customize_glob.yaml
  
  # C for Celcius, F for Fahrenheit
  temperature_unit: C

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http: !include http.yaml

# Edit lovelace interface in yaml   
lovelace: !include lovelace.yaml

logger: !include logger.yaml

# to update duckdns dns record dynamicly
duckdns: !include duckdns.yaml

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true
  
# Discover some devices automatically
discovery:

# mqtt mosquitto broker
mqtt: !include mqtt.yaml

# Media players
media_player: !include media_player.yaml

# Xiaomi zigbee gateway
xiaomi_aqara: !include xiaomi_aqara.yaml

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

recorder:
  #db_url: !secret ha_db_url
  purge_interval: 1
  purge_keep_days: 3

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor yr: !include sensor_yr.yaml

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

sensor: !include sensor.yaml
 
binary_sensor: !include binary_sensor.yaml

switch: !include switch.yaml

device_tracker: !include device_tracker.yaml

zone: !include zone.yaml

history_graph: !include history_graph.yaml

#android_ip_webcam: !include android_ip_webcam.yaml

# Text to speech                      
tts:                                                   
  - platform: google  

# Cloud
cloud:

# Counters
counter: !include counters.yaml

group: !include groups.yaml

automation: !include automations.yaml

script: !include scripts.yaml

