- platform: mqtt
  name: "basic1"
  state_topic: "homeassistant/tele/basic1/STATE"
  value_template: "{{ value_json.POWER }}"
  command_topic: "homeassistant/cmnd/basic1/POWER"
  availability_topic: "homeassistant/tele/basic1/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false
  qos: 2
  retain: true
- platform: mqtt
  name: "basic2"
  state_topic: "homeassistant/tele/basic2/STATE"
  value_template: "{{ value_json.POWER }}"
  command_topic: "homeassistant/cmnd/basic2/POWER"
  availability_topic: "homeassistant/tele/basic2/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false
  qos: 2
  retain: true
- platform: mqtt
  name: "basic3"
  state_topic: "homeassistant/tele/basic3/STATE"
  value_template: "{{ value_json.POWER }}"
  command_topic: "homeassistant/cmnd/basic3/POWER"
  availability_topic: "homeassistant/tele/basic3/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false
  qos: 2
  retain: true
- platform: mqtt
  name: "plug1"
  state_topic: "homeassistant/tele/plug1/STATE"
  value_template: "{{ value_json.POWER }}"
  command_topic: "homeassistant/cmnd/plug1/POWER"
  availability_topic: "homeassistant/tele/plug1/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false
  qos: 2
  retain: true
- platform: mqtt
  name: "plug2"
  state_topic: "homeassistant/tele/plug2/STATE"
  value_template: "{{ value_json.POWER }}"
  command_topic: "homeassistant/cmnd/plug2/POWER"
  availability_topic: "homeassistant/tele/plug2/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false
  qos: 2
  retain: true