kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-haconfig
  labels:
    type: local
spec:
  storageClassName: haconfig
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/homeassistant/config"
