kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-ssl
  labels:
    type: local
spec:
  storageClassName: ssl
  capacity:
    storage: 2Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/home/homeassistant/dehydrated/certs/tedsluis.duckdns.org"
