motion_counter_gang:
  name: bewegingsteller gang
  icon: mdi:account
motion_counter_studeerkamer:
  name: bewegingsteller studeerkamer
  icon: mdi:account
motion_counter_voordeur_buiten:
  name: bewegingsteller voordeur buiten
  icon: mdi:account
motion_counter_keuken:
  name: bewegingsteller keuken
  icon: mdi:account
motion_counter_overloop:
  name: bewegingsteller overloop
  icon: mdi:account
motion_counter_hal:
  name: bewegingsteller hal
  icon: mdi:account
motion_counter_bovenaandetrap:
  name: bewegingsteller boven aan de trap
  icon: mdi:account
motion_counter_steeg:
  name: bewegingsteller steeg
  icon: mdi:account
motion_counter_achterbuiten:
  name: bewegingsteller achter buiten
  icon: mdi:account
