group.all_switches:
  hidden: false


light.the_voice_group_0:
  hidden: true
light.the_voice_group_1:
  hidden: true
light.the_voice_group_2:
  hidden: true
light.the_voice_group_3:
  hidden: true

light.hue_lamp_1:
  hidden: true
light.hue_lamp_2:
  hidden: true
light.hue_lamp_3:
  hidden: true

light.hue_ambiance_light_1:
  hidden: true
light.hue_ambiance_light_1_2:
  hidden: true

light.naud:
  hidden: true
light.hue_lightstrip_1:
  hidden: true

light.lux_lamp_4:
  hidden: true
light.lux_lamp_5:
  hidden: true
light.lux_lamp_6:
  hidden: true


# Friendly names
light.dimmer_3:
  friendly_name: dimmer woonkamer
light.woonkamer_voor:
  friendly_name: woonkamer voor
light.woonkamer_achter:      
  friendly_name: woonkamer achter
light.slaapkamer_annelies_ted:
  friendly_name: slaapkamer annelies en ted
light.slaapkamer_naud:
  friendly_name: ledstrip naud
light.slaapkamer_stijn:
  friendly_name: ledstrip stijn
media_player.bachstraat20:
  friendly_name: Chromecast woonkamer
light.hue_white_light_1:
  friendly_name: overloop
light.hue_white_light_1_2:
  friendly_name: studeerkamer (klein)
light.hue_white_light_1_3:
  friendly_name: voordeur buiten
light.hue_white_light_1_4:
  friendly_name: lamp naud

sensor.yr_temperature:
  friendly_name: temperatuur
sensor.yr_dewpoint_temperature:
  friendly_name: dauwpunt temperatuur
sensor.yr_humidity:
  friendly_name: luchtvochtigheid
  icon: mdi:water-percent
sensor.yr_pressure:
  friendly_name: luchtdruk
  incon: mdi:speedometer
sensor.yr_wind_speed:
  friendly_name: windsnelheid
  icon: mdi:weather-windy
sensor.yr_wind_direction:
  friendly_name: windrichting
  icon: mdi:compass-outline
sensor.yr_precipitation:
  friendly_name: neerslag
  icon: mdi:weather-pouring
sensor.yr_cloudiness:
  friendly_name: bewolking
  icon: mdi:weather-cloudy
sensor.yr_high_clouds:
  friendly_name: hoge bewolking
  icon: mdi:weather-cloudy
sensor.yr_medium_clouds:
  friendly_name: middel hoge bewolking
  icon: mdi:weather-cloudy
sensor.yr_low_clouds:
  friendly_name: lage bewolking
  icon: mdi:weather-cloudy
sensor.yr_fog:
  friendly_name: mist
  icon: mdi:weather-fog

sensor.utrecht_amsterdam_zuid:
  friendly_name: utrecht cs - amsterdam zuid
sensor.amsterdam_zuid_utrecht_cs:
  friendly_name: amsterdam zuid - utrecht cs

sensor.postnl:
  friendly_name: post nl

sensor.speedtest_download:
  friendly_name: download speed
sensor.speedtest_upload:  
  friendly_name: upload speed
sensor.speedtest_ping:  
  friendly_name: latency

sensor.home_assistant_uptime:
  friendly_name: home-assistant uptime
sensor.host_uptime:
  friendly_name: host uptime
sensor.ssl_cert_expiry:
  friendly_name: ssl certificate expiry
sensor.check_hue_bridge:
  friendly_name: hue bridge check
sensor.disk_free:
  friendly_name: disk vrij
sensor.disk_use:
  friendly_name: disk gebruikt
sensor.disk_use_percent:
  friendly_name: percentage disk gebruikt
sensor.memory_use:
  friendly_name: geheugen gebruikt
sensor.memory_free:
  friendly_name: geheugen vrij
sensor.memory_use_percent:
  friendly_name: percentage geheugen gebruikt
sensor.load_1m:
  friendly_name: cpu load 1m
  unit_of_measurement: s
sensor.load_5m:
  friendly_name: cpu load 5m 
  unit_of_measurement: s
sensor.load_15m:
  friendly_name: cpu load 15m 
  unit_of_measurement: s
sensor.network_in_eno1:
  friendly_name: netwerk in
sensor.network_out_eno1:
  friendly_name: netwerk uit
sensor.packets_in_eno1:
  friendly_name: netwerk pakketten in
sensor.packets_out_eno1:
  friendly_name: netwerk pakketten uit

sensor.power_consumption:
  friendly_name: elektriciteitsverbruik 
sensor.power_consumption_low:
  friendly_name: elektriciteitsverbruik laag tarief
sensor.power_consumption_normal:
  friendly_name: elektriciteitsverbruik normaal tarief
sensor.power_consumption_phase_l1:
  friendly_name: verbruik fase l1
sensor.power_consumption_phase_l2:
  hidden: true
sensor.power_consumption_phase_l3:
  hidden: true
sensor.power_production:
  hidden: true 
sensor.power_production_low:
  hidden: true 
sensor.power_production_normal:
  hidden: true 
sensor.power_production_phase_l1:
  hidden: true
sensor.power_production_phase_l2:
  hidden: true
sensor.power_production_phase_l3:
  hidden: true
sensor.power_tariff:
  friendly_name: energie tarief
sensor.voltage_sags_phase_l1:
  friendly_name: spanningsval
sensor.voltage_sags_phase_l2:
  hidden: true
sensor.voltage_sags_phase_l3:
  hidden: true
sensor.voltage_swells_phase_l1:
  friendly_name: spanningspiek 
sensor.voltage_swells_phase_l2:
  hidden: true
sensor.voltage_swells_phase_l3:
  hidden: true
sensor.gas_consumption:
  friendly_name: gasverbruik
sensor.hourly_gas_consumption:
  friendly_name: gasverbruik per uur
sensor.long_power_failure_count:
  friendly_name: langdurige stroomonderbrekingen

#sensor.humidity_158d000231046d:
sensor.omgevingssensorkeuken_humidity:
  battery_sensor_creation_disabled: true
  friendly_name: keuken
#sensor.pressure_158d000231046d:
sensor.omgevingssensorkeuken_pressure:
  battery_sensor_creation_disabled: true
  friendly_name: keuken
#  hidden: true
#sensor.temperature_158d000231046d:
sensor.omgevingssensorkeuken_temperature:
  friendly_name: keuken
  battery_sensor_creation_disabled: true

#sensor.humidity_158d000238fcc1:
sensor.omgevingssensorkamernaud_humidity:
  battery_sensor_creation_disabled: true
  friendly_name: kamer naud
#sensor.pressure_158d000238fcc1:
sensor.omgevingssensorkamernaud_pressure:
  battery_sensor_creation_disabled: true
  friendly_name: kamer naud
#  hidden: true
sensor.omgevingssensorkamernaud_temperature:
#sensor.temperature_158d000238fcc1:
  friendly_name: kamer naud
  battery_sensor_creation_disabled: true

sensor.omgevingssensorkruipruimte_humidity:
  battery_sensor_creation_disabled: true
  friendly_name: kruipruimte
sensor.omgevingssensorkruipruimte_pressure:
  battery_sensor_creation_disabled: true
  friendly_name: kruipruimte
#  hidden: true
sensor.omgevingssensorkruipruimte_temperature:
  friendly_name: kruipruimte
  battery_sensor_creation_disabled: true

sensor.omgevingssensorzolder_humidity:
  battery_sensor_creation_disabled: true
  friendly_name: zolder
sensor.omgevingssensorzolder_pressure:
  battery_sensor_creation_disabled: true
  friendly_name: zolder
#  hidden: true
sensor.omgevingssensorzolder_temperature:
  friendly_name: zolder
  battery_sensor_creation_disabled: true

#binary_sensor.wall_switch_left_158d00026ba474:
#  friendly_name: schakelaar links slaapkamer naud
#binary_sensor.wall_switch_right_158d00026ba474:
#  friendly_name: schakelaar rechts slaapkamer naud
#  battery_sensor_creation_disabled: true
#binary_sensor.wall_switch_both_158d00026ba474:
#  friendly_name: schakelaar beide slaapkamer naud
#  battery_sensor_creation_disabled: true
#
#sensor.humidity_158d00027257cd:
sensor.omgevingssensorkamerstijn_humidity:
  friendly_name: kamer stijn
  battery_sensor_creation_disabled: true
#sensor.pressure_158d00027257cd:
sensor.omgevingssensorkamerstijn_pressure:
  friendly_name: kamer stijn
#  hidden: true
  battery_sensor_creation_disabled: true
#sensor.temperature_158d00027257cd:
sensor.omgevingssensorkamerstijn_temperature:
  friendly_name: kamer stijn
  battery_sensor_creation_disabled: true

#binary_sensor.wall_switch_left_158d00025427e0:
#  friendly_name: schakelaar links slaapkamer stijn
#  battery_sensor_creation_disabled: true
#binary_sensor.wall_switch_right_158d00025427e0:
#  friendly_name: schakelaar rechts slaapkamer stijn
#  battery_sensor_creation_disabled: true
#binary_sensor.wall_switch_both_158d00025427e0:
#  friendly_name: schakelaar beide slaapkamer stijn

#sensor.humidity_158d000273424b:
sensor.omgevingssensorbadkamer_humidity:
  friendly_name: badkamer
  battery_sensor_creation_disabled: true
#sensor.pressure_158d000273424b: 
sensor.omgevingssensorbadkamer_pressure:
  friendly_name: badkamer
  #hidden: true
  battery_sensor_creation_disabled: true
#sensor.temperature_158d000273424b:
sensor.omgevingssensorbadkamer_temperature:
  friendly_name: badkamer
  battery_sensor_creation_disabled: true

#sensor.humidity_158d000273d342:
sensor.omgevingssensorslaapkamer_humidity:
  friendly_name: slaapkamer annelies & ted
  battery_sensor_creation_disabled: true
#sensor.pressure_158d000273d342:
sensor.omgevingssensorslaapkamer_pressure:
  friendly_name: slaapkamer annelies & ted
  #hidden: true
  battery_sensor_creation_disabled: true
#sensor.temperature_158d000273d342:
sensor.omgevingssensorslaapkamer_temperature:
  friendly_name: slaapkamer annelies & ted
  battery_sensor_creation_disabled: true

#binary_sensor.wall_switch_both_158d00027c19e9:
#  hidden: true
#  friendly_name: schakelaar beide slaapkamer annelies & ted
#  battery_sensor_creation_disabled: true
#binary_sensor.wall_switch_left_158d00027c19e9:
#  hidden: true
#  friendly_name: schakelaar links slaapkamer annelies & ted
#  battery_sensor_creation_disabled: true
#binary_sensor.wall_switch_right_158d00027c19e9:
#  hidden: true
#  friendly_name: schakelaar rechts slaapkamer annelies & ted

#light.gateway_light_7c49ebb18b86:
#  friendly_name: nachtlampje slaapkamer annelies & ted
#sensor.illumination_7c49ebb18b86:
#  friendly_name: lichtsensor slaapkamer annelies & ted

#binary_sensor.motion_sensor_158d00029a5cd2:
binary_sensor.bewegingssensoroverloop_occupancy:
  friendly_name: overloop
  battery_sensor_creation_disabled: true
#sensor.illumination_158d00029a5cd2:
sensor.bewegingssensoroverloop_illuminance:
  friendly_name: overloop
  battery_sensor_creation_disabled: true

#sensor.humidity_158d00027725d7:
sensor.omgevingssensorschuur_humidity:
  friendly_name: schuur
  battery_sensor_creation_disabled: true
#sensor.pressure_158d00027725d7:
sensor.omgevingssensorschuur_pressure:
  friendly_name: schuur
#  hidden: true
  battery_sensor_creation_disabled: true
#sensor.temperature_158d00027725d7:
sensor.omgevingssensorschuur_temperature:
  friendly_name: schuur
  battery_sensor_creation_disabled: true
  
#sensor.humidity_158d00027898b3:
sensor.omgevingssensorstudeerkamer_humidity:
  friendly_name: studeerkamer
  battery_sensor_creation_disabled: true
#sensor.pressure_158d00027898b3:
sensor.omgevingssensorstudeerkamer_pressure:
  friendly_name: studeerkamer
#  hidden: true
  battery_sensor_creation_disabled: true
#sensor.temperature_158d00027898b3:
sensor.omgevingssensorstudeerkamer_temperature:
  friendly_name: studeerkamer
  battery_sensor_creation_disabled: true

#binary_sensor.motion_sensor_158d0002584585:
binary_sensor.bewegingssensorstudiekamer_occupancy:
  friendly_name: studeerkamer
  battery_sensor_creation_disabled: true
#sensor.illumination_158d0002584585:
sensor.bewegingssensorstudeerkamer_illuminance:
  friendly_name: studeerkamer
  battery_sensor_creation_disabled: true

#binary_sensor.motion_sensor_158d0002e8d2f1:
binary_sensor.bewegingssensorvoordeur_occupancy:
  friendly_name: voordeur buiten
  battery_sensor_creation_disabled: true
#sensor.illumination_158d0002e8d2f1:
sensor.bewegingssensorvoordeur_illuminance:
  friendly_name: voordeur buiten
  battery_sensor_creation_disabled: true

binary_sensor.bewegingssensorgang_occupancy:
  friendly_name: gang
  battery_sensor_creation_disabled: true
sensor.bewegingssensorgang_illuminance:
  friendly_name: gang
  battery_sensor_creation_disabled: true

binary_sensor.bewegingssensorkeuken_occupancy:
  friendly_name: keuken
  battery_sensor_creation_disabled: true
sensor.bewegingssensorkeuken_illuminance:
  friendly_name: keuken
  battery_sensor_creation_disabled: true

#sensor.humidity_158d0002789adf:
sensor.omgevingssensorwoonkamer_humidity:
  friendly_name: woonkamer 
  battery_sensor_creation_disabled: true
#sensor.pressure_158d0002789adf:
sensor.omgevingssensorwoonkamer_pressure:
  friendly_name: woonkamer
  battery_sensor_creation_disabled: true
#sensor.temperature_158d0002789adf:
sensor.omgevingssensorwoonkamer_temperature:
  friendly_name: woonkamer
  battery_sensor_creation_disabled: true

#switch.plug_158d00024ae109:
#  friendly_name: stopcontact woonkamer

device_tracker.94652dc2aa01:
  friendly_name: Annelies
device_tracker.c0eefbe296aa:
  friendly_name: Ted
device_tracker.44c3462e5fdd:
  friendly_name: Stijn
device_tracker.8058f897ad84:
  friendly_name: Naud
device_tracker.google_maps_103666873320035558501:
  friendly_name: Ted

#binary_sensor.door_window_sensor_158d00025ed544:
binary_sensor.schakelaarvoordeur_contact:
  battery_sensor_creation_disabled: true
  friendly_name: Voordeur
#binary_sensor.door_window_sensor_158d0002e24f96:
binary_sensor.schakelaarachterdeur_contact:
  friendly_name: Achterdeur
  battery_sensor_creation_disabled: true

#binary_sensor.vibration_158d0002b83c5b:
#  friendly_name: Viberate sensor 1
#sensor.bed_activity_158d0002b83c5b:
#  battery_sensor_creation_disabled: true
#sensor.bed_activity_158d0002b83c5b_battery:
#  battery_sensor_creation_disabled: true
#sensor.coordination_158d0002b83c5b:
#  battery_sensor_creation_disabled: true
#sensor.coordination_158d0002b83c5b_battery:
#  battery_sensor_creation_disabled: true
#sensor.tilt_angle_158d0002b83c5b:
#  battery_sensor_creation_disabled: true
#
#binary_sensor.vibration_158d0002b78209:
#  friendly_name: Viberate sensor 2
#sensor.bed_activity_158d0002b78209:
#  battery_sensor_creation_disabled: true
#sensor.bed_activity_158d0002b78209_battery:
#  battery_sensor_creation_disabled: true
#sensor.coordination_158d0002b78209:
#  battery_sensor_creation_disabled: true
#sensor.coordination_158d0002b78209_battery:
#  battery_sensor_creation_disabled: true
#sensor.tilt_angle_158d0002b78209:
#  battery_sensor_creation_disabled: true




sensor.pow1_energy_apparentpower:
  unit_of_measurement: W 
sensor.pow1_energy_factor:
  unit_of_measurement: PF
sensor.pow1_energy_reactivepower:
  unit_of_measurement: W
sensor.pow2_energy_apparentpower:
  unit_of_measurement: W 
sensor.pow2_energy_factor:
  unit_of_measurement: PF
sensor.pow2_energy_reactivepower:
  unit_of_measurement: W

#binary_sensor.0x00158d00025ed544_contact:
#  battery_sensor_creation_disabled: true
#sensor.0x00158d00025ed544_battery:
#  battery_sensor_creation_disabled: true
#sensor.0x00158d00025ed544_contact:
#  friendly_name: Doorswitch1
#
#binary_sensor.0x00158d0002e24f96_battery:
#  battery_sensor_creation_disabled: true
#binary_sensor.0x00158d0002e24f96_contact:
#  friendly_name: Doorswitch2
#sensor.0x00158d00025427e0_battery:
#  battery_sensor_creation_disabled: true
#sensor.0x00158d00025427e0_click:
#  battery_sensor_creation_disabled: true
#
#sensor.viberate_sensor_1_battery:
#  friendly_name: Viberate 1 battery
#sensor.viberate_sensor_2_battery:
#  friendly_name: Viberate 2 battery
#sensor.doorswitch1_contact_battery:
#  friendly_name: Door switch 1 battery
#sensor.doorswitch2_contact_battery:
#  friendly_name: Door switch 2 battery
#sensor.keuken_battery:
#  friendly_name: Sensor kitchen battery
#sensor.lichtsensor_studeerkamer_battery:
#  friendly_name: Motion study room battery 
#sensor.lichtsensor_voordeur_buiten_battery:
#  friendly_name: Motion front door battery
#sensor.schuur_battery:
#  friendly_name: Sensor barn battery
#sensor.slaapkamer_annelies_ted_battery:
#  friendly_name: Sensor master bedroom battery
#sensor.slaapkamer_naud_battery:
#  friendly_name: Sensor bedroom Naud battery
#sensor.stopcontact_woonkamer_battery:
#  friendly_name: Power plug livingroom battery
#sensor.switchstijn_click_battery:
#  friendly_name: Switch Stijn battery
sensor.ted_battery:
  friendly_name: Mobile phone battery
#sensor.woonkamer_battery:
#  friendly_name: Sensor living room
#sensor.schakelaar_links_slaapkamer_naud_battery:
#  friendly_name: Schakelaar Naud battery
#sensor.lichtsensor_overloop_battery:
#  friendly_name: Motion corridor 1st floor battery

