# Name of the location where Home Assistant is running
name: Home

auth_providers:
  - type: homeassistant
  - type: legacy_api_password
    api_password: !secret api_password
  - type: trusted_networks
    trusted_networks:
      - 192.168.11.0/24

# Location required to calculate the time the sun rises and sets
# Impacts weather/sunrise data (altitude above sea level in meters)
latitude: !secret latitude_home
longitude: !secret longitude_home

# Impacts weather/sunrise data (altitude above sea level in meters)
elevation: !secret elevation

# metric for Metric, imperial for Imperial
unit_system: metric

# Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
time_zone: Europe/Amsterdam

# Customization file
customize: !include customize.yaml

# customize glob file
customize_glob: !include customize_glob.yaml

# C for Celcius, F for Fahrenheit
temperature_unit: C
