base_url: !secret my_base_url
# Letsencrypt duckdns for home-assistant: https://www.splitbrain.org/blog/2017-08/10-homeassistant_duckdns_letsencrypt
ssl_certificate: /ssl/fullchain.pem
ssl_key: /ssl/privkey.pem
ip_ban_enabled: True
login_attempts_threshold: 50

# Depricated - moved to auth_providers.
#api_password: !secret api_password
#trusted_networks: 
#  - !secret trusted_networks

