broker: 192.168.11.100
discovery_prefix: homeassistant
discovery: true
username: !secret mqtt_username
password: !secret mqtt_password
birth_message:
  topic: 'hass/status'
  payload: 'online'
will_message:
  topic: 'hass/status'
  payload: 'offline'
