apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ha.fullname" . }}-homeassistant
  labels:
{{ include "ha.labels" . | indent 4 }}
    app: {{ include "ha.fullname" . }}-homeassistant
spec:
  replicas: {{ .Values.homeassistant.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ha.name" . }}-homeassistant
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ha.name" . }}-homeassistant
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: pvc-homeassistant-storage
          persistentVolumeClaim:
            claimName: pvc-homeassistant
        - name: pvc-ssl-storage
          persistentVolumeClaim:
            claimName: pvc-ssl
        - name: pvc-localtime-storage
          persistentVolumeClaim:
            claimName: pvc-localtime
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.homeassistant.image.repository }}:{{ .Values.homeassistant.image.tag }}"
          imagePullPolicy: {{ .Values.homeassistant.image.pullPolicy }}
          ports:
            - name: api
              containerPort: 8123
              protocol: TCP
          volumeMounts:
            - mountPath: "/config"
              name: pvc-homeassistant-storage
            - mountPath: "/ssl"
              name: pvc-ssl-storage
            - mountPath: "/etc/localtime"
              name: pvc-localtime-storage
          livenessProbe:
            httpGet:
              path: /
              port: api
              scheme: HTTPS
            initialDelaySeconds: 120
            failureThreshold: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: api
              scheme: HTTPS
            initialDelaySeconds: 120
            failureThreshold: 5
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.homeassistant.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
