kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-homeassistant
  labels:
    type: local
spec:
  storageClassName: homeassistant
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/homeassistant/config"
