apiVersion: v1
kind: Service
metadata:
  name: {{ include "ha.fullname" . }}-homeassistant
  labels:
{{ include "ha.labels" . | indent 4 }}
    app: {{ include "ha.fullname" . }}-homeassistant
spec:
  type: {{ .Values.homeassistant.service.type }}
  ports:
    - port: {{ .Values.homeassistant.service.port }}
      targetPort: 8123
      protocol: TCP
      name: api
  selector:
    app.kubernetes.io/name: {{ include "ha.name" . }}-homeassistant
    app.kubernetes.io/instance: {{ .Release.Name }}
