apiVersion: v1
kind: Service
metadata:
  name: {{ include "ha.fullname" . }}-influxdb
  labels:
{{ include "ha.labels" . | indent 4 }}
    app: {{ include "ha.fullname" . }}-influxdb
spec:
  type: {{ .Values.influxdb.service.type }}
  ports:
    - port: {{ .Values.influxdb.service.httpport }}
      targetPort: 8086
      protocol: TCP
      name: http
    - port: {{ .Values.influxdb.service.adminport }}
      targetPort: 8083
      protocol: TCP
      name: admin
  selector:
    app.kubernetes.io/name: {{ include "ha.name" . }}-influxdb
    app.kubernetes.io/instance: {{ .Release.Name }}
