apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ha.fullname" . }}-mqtt
  labels:
{{ include "ha.labels" . | indent 4 }}
    app: {{ include "ha.fullname" . }}-mqtt
spec:
  replicas: {{ .Values.mqtt.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ha.name" . }}-mqtt
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ha.name" . }}-mqtt
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: pvc-mqtt-etc-storage
          persistentVolumeClaim:
            claimName: pvc-mqtt-etc
        - name: pvc-mqtt-log-storage
          persistentVolumeClaim:
            claimName: pvc-mqtt-log
        - name: pvc-mqtt-data-storage
          persistentVolumeClaim:
            claimName: pvc-mqtt-data
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.mqtt.image.repository }}:{{ .Values.mqtt.image.tag }}"
          imagePullPolicy: {{ .Values.mqtt.image.pullPolicy }}
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
            - name: websocket
              containerPort: 9001
              protocol: TCP
          volumeMounts:
            - mountPath: "/mosquitto/config"
              name: pvc-mqtt-etc-storage
            - mountPath: "/mosquitto/log"
              name: pvc-mqtt-log-storage
            - mountPath: "/mosquitto/data"
              name: pvc-mqtt-data-storage
          livenessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 60
          readinessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 60
          resources:
            {{- toYaml .Values.mqtt.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
