kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-mqtt-data
  labels:
    type: local
spec:
  storageClassName: mqtt-data
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/homeassistant/mosquitto/data"
