apiVersion: v1
kind: Service
metadata:
  name: {{ include "ha.fullname" . }}-mqtt
  labels:
{{ include "ha.labels" . | indent 4 }}
    app: {{ include "ha.fullname" . }}-mqtt
spec:
  type: {{ .Values.mqtt.service.type }}
  ports:
    - port: {{ .Values.mqtt.service.mqttport }}
      targetPort: 1883
      protocol: TCP
      name: mqtt
    - port: {{ .Values.mqtt.service.websocketport }}
      targetPort: 9001
      protocol: TCP
      name: websocket
  selector:
    app.kubernetes.io/name: {{ include "ha.name" . }}-mqtt
    app.kubernetes.io/instance: {{ .Release.Name }}
