homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://xxx.xxx.xxx.xxx'
  user: *********
  password: *************
  reject_unauthorized: false
  include_device_information: true
zigbee_shepherd_devices: false
serial:
  port:    /dev/ttyACM0
  #disable_led: true
advanced:
  network_key: [ xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx]]
  pan_id: 0x165a
  ext_pan_id: [ xxx,xxx,xxx,xxx,xxx,xxx,xxx,xxx]]
  channel: 26
  cache_state: true
  log_level: info
  last_seen: ISO_8601
  elapsed: false
  availability_timeout: 30
  report: true
  rtscts: true
  homeassistant_discovery_topic: homeassistant
  homeassistant_status_topic: hass/status
map_options:
  graphviz:
    colors:
      fill:
        enddevice: '#fff8ce'
        coordinator: '#e04e5d'
        router: '#4ea3e0'
      font:
        coordinator: '#ffffff'
        router: '#ffffff'
        enddevice: '#000000'
      line:
        active: '#009900'
        inactive: '#994444'
#queue:
#  delay: 250
#  simultaneously: 5
device_options:
  retain: false
  qos: 1
  debounce: 1
  debounce_ignore:
  - action
  - brightness
  - occupancy
  - light
  - switch_l1
  - switch_l2
  - switch
  - contact
  - click
devices: devices.yaml
groups: groups.yaml
