homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt:/***.***.***.***
  user: ********
  password: ******************
  reject_unauthorized: false
  include_device_information: true
serial:
  port: /dev/ttyACM0
  #disable_led: true
advanced:
  network_key:
    - 33
    - 20
    - 198
    - 168
    - 91
    - 37
    - 241
    - 250
    - 238
    - 131
    - 255
    - 77
    - 30
    - 189
    - 97
    - 119
  #pan_id: 6754
  pan_id: 0x165a
  ext_pan_id:
    - 221
    - 121
    - 221
    - 121
    - 221
    - 221
    - 121
    - 221
  channel: 26
  cache_state: true
  log_level: debug
  last_seen: ISO_8601
  elapsed: false
  availability_timeout: 0
  availability_blacklist:
    - DEVICE_FRIENDLY_NAME
  report: true
  homeassistant_discovery_topic: homeassistant
  homeassistant_status_topic: hass/status
map_options:
  graphviz:
    colors:
      fill:
        enddevice: '#fff8ce'
        coordinator: '#e04e5d'
        router: '#4ea3e0'
      font:
        coordinator: '#ffffff'
        router: '#ffffff'
        enddevice: '#000000'
      line:
        active: '#009900'
        inactive: '#994444'
queue:
  delay: 250
  simultaneously: 5
device_options: null
devices: devices.yaml
groups: groups.yaml
